[tool.poetry]
name = "dummy"
version = "0.1.0"
description = ""
authors = ["levan <levan.bujiashvili.1@btu.edu.ge>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
